FROM phusion/baseimage:0.11

RUN apt-get update \
  && apt-get install -y --no-install-recommends \
  gcc \
  libsqlite3-dev \
  libssl-dev \
  libffi-dev \
  python3 \
  python3-dev \
  python3-pip \
  python3-setuptools \
  python3-wheel \
  && rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/*

WORKDIR /app

COPY src src/
WORKDIR /app/src
RUN pip3 install -r requirements.txt && pip3 install reprozip==1.0.14

COPY config/reprozip/run.sh ./

CMD ["bash", "run.sh"]
