FROM phusion/baseimage:0.11

RUN apt-get update \
  && apt-get install -y libsqlite3-dev python3-pip \
  && rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/*

WORKDIR /app

COPY src src/
WORKDIR /app/src
RUN pip3 install -r requirements.txt \
  && pip3 install reprozip==1.0.14

COPY config/reprozip/run.sh .
COPY config/reprozip/additional_patterns.yml .

CMD ["bash", "run.sh"]
